### PR TITLE
adding fixtures/tdp_initial_data.json to the whl

### PR DESCRIPTION
**Pull request by nbucknor**
## Additions

- Adding the missing tdp_initial_data.json file to the whl

### CODE REVIEW

**Comment by nbucknor** [comment]
@Scotchester @higs4281 If it's OK with you. I'm just going to merge this into master and send another bump request to cfgov-refresh

**Comment by Scotchester** [comment]
@nbucknor Did you build the wheel locally and confirm that the file gets in there?

**Comment by nbucknor** [comment]
@Scotchester ... I have now ;-). The file is there.

**Comment by nbucknor** [comment]
Had to convert the wheel file to zip in order to upload it here.
[teachers_digital_platform-1.0.5.dev3+4378f10-py2-none-any.zip](https://github.com/cfpb/teachers-digital-platform/files/2229389/teachers_digital_platform-1.0.5.dev3%2B4378f10-py2-none-any.zip)

**Pull request merged**
