### PR TITLE
[HOLD] TDP CR Tool fix unit tests

### PR DESCRIPTION
**Pull request by nbucknor**
Changes to package.json and CR Tool unit tests so they no longer fail

## Testing

1. run `./setup.sh`
2. run `npm test`
3. run `tox -e lint`

All should run without error*

* Note: there will be warnings for tox, but it should still pass

### CODE REVIEW

**Comment by dcmouyard** [comment]
I got the following error when running `./setup.sh`:
```
npm components directory: node_modules
crtool npm components directory: teachers_digital_platform/crtool/node_modules
Clean & Install
Removing project dependency directories… $NODE_DIR
Project dependencies have been removed.
Removing project dependency directories… $CRTOOL_NODE_DIR
Project dependencies have been removed.
Installing front-end dependencies…

> fsevents@1.2.9 install /Users/mouyardd/projects/cfgov-refresh/develop-apps/teachers-digital-platform/node_modules/fsevents
> node install

node-pre-gyp WARN Using request for node-pre-gyp https download 
[fsevents] Success: "/Users/mouyardd/projects/cfgov-refresh/develop-apps/teachers-digital-platform/node_modules/fsevents/lib/binding/Release/node-v57-darwin-x64/fse.node" is installed via remote

> uglifyjs-webpack-plugin@0.4.6 postinstall /Users/mouyardd/projects/cfgov-refresh/develop-apps/teachers-digital-platform/node_modules/uglifyjs-webpack-plugin
> node lib/post_install.js


> django-satellite-app@1.0.0 postinstall /Users/mouyardd/projects/cfgov-refresh/develop-apps/teachers-digital-platform
> cd teachers_digital_platform/crtool && npm install


> fsevents@1.2.9 install /Users/mouyardd/projects/cfgov-refresh/develop-apps/teachers-digital-platform/teachers_digital_platform/crtool/node_modules/chokidar/node_modules/fsevents
> node install

node-pre-gyp WARN Using request for node-pre-gyp https download 
[fsevents] Success: "/Users/mouyardd/projects/cfgov-refresh/develop-apps/teachers-digital-platform/teachers_digital_platform/crtool/node_modules/chokidar/node_modules/fsevents/lib/binding/Release/node-v57-darwin-x64/fse.node" is installed via remote

> fsevents@1.2.9 install /Users/mouyardd/projects/cfgov-refresh/develop-apps/teachers-digital-platform/teachers_digital_platform/crtool/node_modules/jest-haste-map/node_modules/fsevents
> node install

node-pre-gyp WARN Using request for node-pre-gyp https download 
[fsevents] Success: "/Users/mouyardd/projects/cfgov-refresh/develop-apps/teachers-digital-platform/teachers_digital_platform/crtool/node_modules/jest-haste-map/node_modules/fsevents/lib/binding/Release/node-v57-darwin-x64/fse.node" is installed via remote

> core-js@3.1.4 postinstall /Users/mouyardd/projects/cfgov-refresh/develop-apps/teachers-digital-platform/teachers_digital_platform/crtool/node_modules/react-app-polyfill/node_modules/core-js
> node scripts/postinstall || echo "ignore"

added 1702 packages from 839 contributors and audited 1791854 packages in 42.544s
found 0 vulnerabilities

added 1637 packages from 988 contributors and audited 895689 packages in 79.643s
found 0 vulnerabilities

Building project…
Requiring task ./gulp/tasks/clean.js
Requiring task ./gulp/tasks/copy.js
Requiring task ./gulp/tasks/crtool.js
Requiring task ./gulp/tasks/lint.js
Requiring task ./gulp/tasks/scripts.js
Requiring task ./gulp/tasks/styles.js
Requiring task ./gulp/tasks/test-unit.js
defining test task
[15:45:41] Using gulpfile ~/projects/cfgov-refresh/develop-apps/teachers-digital-platform/gulpfile.js
[15:45:41] Starting 'build'...
[15:45:41] Starting 'styles'...
[15:45:41] Starting 'scripts'...
[15:45:41] Starting 'crtool'...
[15:45:41] Starting 'styles:modern'...
[15:45:41] Starting 'scripts:modern'...

> tdp-prototype@0.1.0 build /Users/mouyardd/projects/cfgov-refresh/develop-apps/teachers-digital-platform/teachers_digital_platform/crtool
> react-scripts build --debug && mkdir -p ../static/tdp/js && mv build/static/**/main*.js ../static/tdp/js/crtool.react.v1.js && mv build/static/js/main*.map ../static/tdp/js/

(node:33291) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
[15:45:42] src: teachers_digital_platform/css/tdp.less
[15:45:42] src: 1 item

There might be a problem with the project dependency tree.
It is likely not a bug in Create React App, but something you need to fix locally.

The react-scripts package provided by Create React App requires a dependency:

  "babel-jest": "^24.8.0"

Don't try to install it manually: your package manager does it automatically.
However, a different version of babel-jest was detected higher up in the tree:

  /Users/mouyardd/projects/cfgov-refresh/node_modules/babel-jest (version: 24.7.1) 

Manually installing incompatible versions is known to cause hard-to-debug issues.

If you would prefer to ignore this check, add SKIP_PREFLIGHT_CHECK=true to an .env file in your project.
That will permanently disable this message but you might encounter other issues.

To fix the dependency tree, try following the steps below in the exact order:

  1. Delete package-lock.json (not package.json!) and/or yarn.lock in your project folder.
  2. Delete node_modules in your project folder.
  3. Remove "babel-jest" from dependencies and/or devDependencies in the package.json file in your project folder.
  4. Run npm install or yarn, depending on the package manager you use.

In most cases, this should be enough to fix the problem.
If this has not helped, there are a few other things you can try:

  5. If you used npm, install yarn (http://yarnpkg.com/) and repeat the above steps with it instead.
     This may help because npm has known issues with package hoisting which may get resolved in future versions.

  6. Check if /Users/mouyardd/projects/cfgov-refresh/node_modules/babel-jest is outside your project directory.
     For example, you might have accidentally installed something in your home folder.

  7. Try running npm ls babel-jest in your project folder.
     This will tell you which other package (apart from the expected react-scripts) installed babel-jest.

If nothing else helps, add SKIP_PREFLIGHT_CHECK=true to an .env file in your project.
That would permanently disable this preflight check in case you want to proceed anyway.

P.S. We know this message is long but please read the steps above :-) We hope you find them helpful!

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tdp-prototype@0.1.0 build: `react-scripts build --debug && mkdir -p ../static/tdp/js && mv build/static/**/main*.js ../static/tdp/js/crtool.react.v1.js && mv build/static/js/main*.map ../static/tdp/js/`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the tdp-prototype@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mouyardd/.npm/_logs/2019-09-18T19_45_43_421Z-debug.log
[15:45:43] 'crtool' errored after 1.48 s
[15:45:43] Error: 1
    at formatError (/Users/mouyardd/.nvm/versions/node/v8.11.1/lib/node_modules/gulp-cli/lib/versioned/^4.0.0/format-error.js:20:10)
    at Gulp.<anonymous> (/Users/mouyardd/.nvm/versions/node/v8.11.1/lib/node_modules/gulp-cli/lib/versioned/^4.0.0/log/events.js:31:15)
    at emitOne (events.js:121:20)
    at Gulp.emit (events.js:211:7)
    at Object.error (/Users/mouyardd/projects/cfgov-refresh/develop-apps/teachers-digital-platform/node_modules/undertaker/lib/helpers/createExtensions.js:61:10)
    at handler (/Users/mouyardd/projects/cfgov-refresh/develop-apps/teachers-digital-platform/node_modules/now-and-later/lib/map.js:50:14)
    at f (/Users/mouyardd/projects/cfgov-refresh/develop-apps/teachers-digital-platform/node_modules/once/once.js:25:25)
    at f (/Users/mouyardd/projects/cfgov-refresh/develop-apps/teachers-digital-platform/node_modules/once/once.js:25:25)
    at tryCatch (/Users/mouyardd/projects/cfgov-refresh/develop-apps/teachers-digital-platform/node_modules/async-done/index.js:24:15)
    at ChildProcess.done (/Users/mouyardd/projects/cfgov-refresh/develop-apps/teachers-digital-platform/node_modules/async-done/index.js:40:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
[15:45:43] 'build' errored after 1.48 s
[15:45:43] The following tasks did not complete: styles, scripts, styles:modern, scripts:modern
[15:45:43] Did you forget to signal async completion?
```

**Comment by anselmbradford** [comment]
@dcmouyard try upgrading your node to v10.x

**Comment by dcmouyard** [comment]
The above error message went away after I updated node from `v8.11.1` to `v12.10.0`.

**Comment by dcmouyard** [comment]
@nbucknor The unit tests are working for me now that I’ve updated Node to `v12.10.0`.

**Comment by nbucknor** [comment]
Thanks @anselmbradford! Were you able to review this branch as well?

**Comment by nbucknor** [comment]
Closed in favor of https://github.com/cfpb/teachers-digital-platform/pull/354

**Pull request closed without merging**
