### PR TITLE
[CRTOOL] correcting analytics

### PR DESCRIPTION
**Pull request by nbucknor**
Correcting the analytics labels and events to match @kelleyholden 's specifications
See: https://github.com/cfpb/teachers-digital-platform/pull/369#issuecomment-597195573
## Changes
- Updated the the following analytics variables:
    - "link clicked: Remove efficacy study", "Remove" => "link click", "remove efficacy study"
    - "Remove efficacy study modal", linkText => "efficacy modal", linkText

## Review

- @Scotchester @kelleyholden

### CODE REVIEW

**Comment by nbucknor** [comment]
Thanks for reviewing this @Scotchester. I figured since the original Analytics event for removing the study was the same, I didn't need to change it. But it's a good idea to confirm with Kelley. @kelleyholden did you want to change the analytics event for when the Study is actually removed? It's currently set to:

event category (keep the same): curriculum review tool interaction
event action: "button clicked"
event label: "Remove"

**Comment by nbucknor** [comment]
@kelleyholden did you get a chance to review this?

**Comment by kelleyholden** [comment]
@nbucknor SO SORRY! I didn't realize i was filtering these out of my inbox (just set up a bunch of new filters) - i'll check to today and get back to you ASAP

**Comment by kelleyholden** [comment]
@nbucknor yes let's update that to what i suggested, to keep it consistent with the rest of the modal.

**Comment by nbucknor** [comment]
Thanks @kelleyholden. Will do.

**Comment by kelleyholden** [comment]
@nbucknor that works thank you! let me know when you'd like me to test.

**Comment by kelleyholden** [comment]
hey! any updates on this?

**Pull request merged**
