### PR TITLE
Updates jsdoc to no longer depend on a vulnerable package

### PR DESCRIPTION
**Pull request by wpears**
Low severity as this is just a devdep, but this'll get the big yellow notice off.

### CODE REVIEW

**Comment by anselmbradford** [comment]
Unfortunately, they need another release https://github.com/jsdoc3/jsdoc/issues/1489

**Comment by wpears** [comment]
You sure? Check out the lockfile diff, looks like it updates to 0.3.9 to me.

**Comment by anselmbradford** [comment]
How bout that. ¯\_(ツ)_/¯ okay then.

**Comment by ascott1** [comment]
I re-ran the travis tests and everything looks good. Merging.

**Pull request merged**
